import { ThemeProvider } from 'next-themes';
import { Navbar, Footer } from '../components/';
import Script from 'next/script';
import './globals.css';

export const metadata = {
  title: 'nft marketplace',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body>
        <ThemeProvider attribute='class' defaultTheme='light'>
          <div className='dark:bg-nft-dark bg-white min-h-screen'>
            <Navbar />
            <div className='pt-65'>{children}</div>
            <Footer />
            <Script
              src='https://kit.fontawesome.com/e61a49ce78.js'
              crossorigin='anonymous'
            />
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
